# Development stage
FROM node:22-alpine as dev

# Define working directory in container
WORKDIR /app

# Copy package.json and package-lock.json to container
COPY axels-cinema/package*.json ./
RUN npm install

# Copy all files to container
COPY axels-cinema/ .

# Expose the port Vite runs on
EXPOSE 5173

# Start app in dev
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]


# Build stage
FROM node:22-alpine as build

# Define working directory in container
WORKDIR /app

# Copy package.json and package-lock.json to container
COPY axels-cinema/package*.json ./
RUN npm install

# Copy all files to container
COPY axels-cinema/ .

RUN npm run build


# Production stage
FROM nginx:alpine as prod

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]